#pragma once

#include "NowPlayingPresenter.h"

namespace adv_walkman {
namespace player {

struct P3BCheckResult {
    uint16_t checks = 0;
    const char* failure = nullptr;
    bool passed() const { return checks != 0 && failure == nullptr; }
};

// Compiled now, invoked by the later combined Gate BEFORE audio starts.
// These do not use the real Player, modify volume or write to SD.
P3BCheckResult checkP3BModel();
P3BCheckResult checkP3BDrawing(lgfx::LovyanGFX& scratchRow);
P3BCheckResult checkP3BPresenterDrawing(NowPlayingPresenter& presenter);
P3BCheckResult checkP3BOverlayRestoration(NowPlayingPresenter& presenter);

// Reusable combined-Gate support. Capture during a continuous Playing window
// AFTER the Gate resets Player diagnostics; write only after stopping audio.
// No P3B PASS is generated by the existing P3A Gate or ordinary app.
class P3BValidation final {
  public:
    void begin(const char* path, uint32_t nowMs);
    void sample(const PlayerSnapshot& audio, const NowPlayingPresenter& ui,
                 uint32_t nowMs);
    bool writeLog(fs::FS& fs, const P3BCheckResult& modelChecks,
                   const P3BCheckResult& drawChecks,
                   const P3BCheckResult& overlayChecks,
                   bool displayConfirmed, bool overlayConfirmed) const;
    const char* audioFailure() const { return audioFailure_; }

  private:
    char path_[kTrackPathCapacity]{};
    bool started_ = false;
    uint32_t startedMs_ = 0;
    uint32_t elapsedMs_ = 0;
    uint32_t samples_ = 0;
    uint32_t lastBufferCount_ = 0;
    const char* audioFailure_ = nullptr;
    PlayerSnapshot audio_;
    NowPlayingRenderStats render_;
    DisplayMetadataState metadataState_ = DisplayMetadataState::Fallback;
    uint8_t metadataWarning_ = 0;
    MarqueePhase phase_ = MarqueePhase::Static;
    uint8_t observedPhases_ = 0;
    uint32_t cycles_ = 0;
    uint32_t staleResults_ = 0;
    uint8_t rawRepeat_ = 0;
    bool rawShuffle_ = false;
};

}  // namespace player
}  // namespace adv_walkman
